server:
  port: 8000
  servlet:
    context-path: /site
    encoding:
      charset: UTF-8
      enabled: true
      force: true

jpa:
  open-in-view: true
  hibernate:
    ddl-auto: create
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardlmpl
    use-new-id-generator-mapping: false
    show-sql: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**