server:
  port: 8000
  servlet:
    context-path: /site
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: root
    password: MySQL

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        use-new-id-generator-mappings: false #jpa가 사용하 기본 넘버링을 사용하지 않는다.
    show-sql: true    #이것으로 실행하였을 때 콘솔창에 나타난다.
    properties:
      hibernate.format_sql: true  #원래는 실행하면 한 줄로 나타나는데 이것으로 줄이 정렬되어 나타난다.

  jackson:
    serialization:
      fail-on-empty-beans: false



